import { redirect } from "next/navigation"
import Image from "next/image"
import { headers } from 'next/headers'
import { NavItem, SideNav } from "@fet/components"
import auth from "@fet/auth"
import LogoutButton from "./LogoutButton"
import type { Metadata } from "next"

export const metadata:Metadata = {
  title: `Create Next App`,
  description: `Generated by create next app`,
}

const navItems:NavItem[] = [
  { label:`Dysk`, href:`/drive` },
  { label: `Mapa`, href:`/map` },
]

export default async function RootLayout({ children }:Readonly<{ children: React.ReactNode }>) {
  const headersList = await headers()
  const currentPath = headersList.get( `x-invoke-path` )

  const isAuth = await auth()
  console.log( isAuth?.session )
  if (!isAuth) redirect( `/login?redirectUrl=${currentPath}` )

  return (
    <>
      <SideNav
        items={navItems} className="absolute top-0 left-[20px] rounded-md right-[20px] top-2 p-2 bg-gray-700 text-gray-50"
        logo={<><Image alt="" width="20" height="20" src="logo.svg" /> </>}
        logoutBtn={<LogoutButton />}
      />
      <div className="pt-15 mx-[20px]">
        {children}
      </div>
    </>
  )
}
