POST http://localhost:3000/api/drive?path=/adam-1/test.txt&override

{
    "Name":2
}


###

POST http://localhost:3000/api/drive?path=/adam-1/mf.png&override

< ./sc.png

###
GET http://localhost:3000/api/drive?path=/adam-1/mf.png

###
DELETE  http://localhost:3000/api/drive?path=/adam-1/mf.png
