###

POST http://localhost:3000/api/memory-db?key=test2
Content-Type: application/json

[1,2,3]


###
GET http://localhost:3000/api/memory-db?key=test2


###
DELETE  http://localhost:3000/api/memory-db?key=test3
