###

POST http://localhost:3000/api/memory-db?key=test2
Content-Type: application/json

{
    "Name":2
}


###
GET http://localhost:3000/api/memory-db?key=test3


###
DELETE  http://localhost:3000/api/memory-db?key=test3
